#server:
#  port: 8071
spring:
#  application:
#    name: mseureka-servicio


  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ESTUDIANTE
    password: 123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost